# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: El periodista como programador
email: david.ruiz@unir.net
description: Esta es una prueba de uso de jekyll en cloud9. Recuerda que para servirla aquí tienes que ejecutar jekyll serve --host $IP --port $PORT --baseurl ''
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ruizfrontend
github_username:  ruizfrontend

# Build settings
markdown: kramdown
